kind: wasmer.io/App.v0
name: digitech-portal
app_id: da_R36ILtlUQX47
owner: kplonzame102k09
package: .
locality:
  regions:
  - us-losa1
capabilities:
  instaboot:
    mode: null
    requests:
    - path: /
    - path: /auth/login
    - path: /request-account
  database:
    engine: mysql
volumes:
- name: data
  mount: /app/storage/app
debug: true
scaling:
  mode: single_concurrency
jobs:
- name: migrate
  trigger: post-deployment
  action:
    execute:
      command: migrate
enable_email: true
