kind: wasmer.io/App.v0
name: digitech-portal
owner: kplonzame102k09
package: .

enable_email: true

volumes:
  - name: data
    mount: /app/storage/app

capabilities:
  database:
    engine: mysql
  instaboot:
    requests:
      - path: /
      - path: /auth/login
      - path: /request-account

health_checks:
  - http:
      method: get
      path: /
      interval: 30s
      timeout: 10s
      unhealthy_threshold: 2
      healthy_threshold: 1
      expected_status_codes:
        - 200

locality:
  regions:
    - us-losa1

scaling:
  mode: single_concurrency

jobs:
  - name: migrate
    trigger: post-deployment
    action:
      execute:
        command: migrate
        timeout: 10m