[package]
name = "digitech-portal"
version = "1.0.0"
namespace = "kplonzame102k09"

[dependencies]
"php/php" = "=8.3.4"

[fs]
"/app/" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-d", "upload_max_filesize=20M", "-d", "post_max_size=25M", "-d", "memory_limit=256M", "-t", "/app/public", "-S", "localhost:8080"]

[[command]]
name = "migrate"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-d", "memory_limit=256M", "/app/artisan", "migrate", "--force"]

[[command]]
name = "debug"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-r", "phpinfo();"]